apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-deployment
  labels:
    app: stable-diffusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      labels:
        app: stable-diffusion
    spec:
      nodeName: selab-t27
      restartPolicy: Always
      initContainers:
      - name: stable-diffusion-initial
        image: library/sd-comfy:latest
        imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
        - "cp -r /stable-diffusion-comfyui /stable-diffusion-comfyui-data"
        volumeMounts:
        - name: sd-backup
          mountPath: /stable-diffusion-comfyui-data
      containers:
      - name: stable-diffusion-comfyui
        image: library/sd-comfy:latest
        imagePullPolicy: Never
        command: ["python3", "/stable-diffusion-comfyui/main.py"]
        args:
        #------------for comfyui----------------
        - "--listen"
        - "--disable-auto-launch"

        #------------for sd.ui----------------
        # - "--listen"
        # - "--xformers"
        # - "--no-download-sd-model"
        # - "--enable-insecure-extension-access"
        # - "--api"
        # - "--disable-safe-unpickle"

        #------------for sd.next----------------
        # - "--theme=dark"
        # - "--insecure"
        # - "--allow-code"
        # - "--listen"
        # - "--upgrade"
        # - "--no-download"
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8188
        volumeMounts:
        - name: sd-data
          mountPath: /stable-diffusion-comfyui
        - name: sd-model-checkpoints
          mountPath: /stable-diffusion-comfyui/models/checkpoints   
        - name: sd-model-lora
          mountPath: /stable-diffusion-comfyui/models/loras   
        - name: sd-model-upscale
          mountPath: /stable-diffusion-comfyui/models/upscale_models
        - name: sd-embeddings
          mountPath: /stable-diffusion-comfyui/models/embeddings    
        - name: sd-controlnet
          mountPath: /stable-diffusion-comfyui/models/controlnet
        - name: sd-vae
          mountPath: /stable-diffusion-comfyui/models/vae
        - name: sd-animatediff-model
          mountPath: /stable-diffusion-comfyui/custom_nodes/ComfyUI-AnimateDiff-Evolved/models
      - name: stable-diffustion-ux
        image: library/sdwebui-ux:latest
        imagePullPolicy: Never
        command: ["python3", "/stable-diffusion-webui/launch.py"]
        args:
                #------------for sd.ui----------------
        - "--listen"
        - "--no-download-sd-model"
        - "--enable-insecure-extension-access"
        - "--no-half"
        - "--skip-torch-cuda-test"
        ports:
        - containerPort: 7860
        volumeMounts:
        - name: sd-ux-data
          mountPath: /stable-diffusion-webui
      volumes:
      - name: sd-backup
        hostPath:
          path: /home/selab
      - name: sd-data
        hostPath:
          path: /home/selab/stable-diffusion-comfyui
      - name: sd-ux-data
        hostPath:
          path: /home/selab/stable-diffusion-webui
      - name: sd-model-checkpoints
        hostPath:
          path: /home/selab/stable-diffusion-webui/models/Stable-diffusion
      - name: sd-model-lora
        hostPath:
          path: /home/selab/stable-diffusion-webui/models/Lora   
      - name: sd-model-upscale
        hostPath:
          path: /home/selab/stable-diffusion-webui/models/ESRGAN             
      - name: sd-controlnet
        hostPath:
          path: /home/selab/ControlNet-v1-1/
      - name: sd-embeddings
        hostPath:
          path: /home/selab/stable-diffusion-webui/models/embeddings
      - name: sd-vae
        hostPath:
          path: /home/selab/stable-diffusion-webui/models/VAE
      - name: sd-animatediff-model
        hostPath: 
          path: /home/selab/stable-diffusion-webui/extensions/sd-webui-animatediff/model

---
apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-service
  labels:
    app: stable-diffusion-service
spec:
  type: NodePort
  selector:
    app: stable-diffusion
  ports:
    - name: comfyui
      protocol: TCP
      port: 8188
      targetPort: 8188
      nodePort: 30818
    - name: uiux
      protocol: TCP
      port: 7860
      targetPort: 7860
      nodePort: 30786
